Feat/sm 131
mchekini-check-consulting/staff-manager-admin-ui pull request #2
Opened 2023-07-10 19:55 UTC by HL-Abdallah

## Client list + creation button :
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/68193549/de7b4e1e-ed83-4373-9da6-723cbb2e5ab2)

## Creation modal : 
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/68193549/8e18df19-c63d-4bc6-b5be-89fe7fc2a863)

2023-07-10 20:58 UTC, xlincw0w requested changes
Merci pour ton travail Abdallah tout est parfait j'ai juste une remarque en plus des console log
si tu me le permet qui est de reset le formulaire après annulation

2023-07-10 20:58 UTC, xlincw0w commented on src/layouts/Clients/ClientList.js
> +    console.log("data", data);
Ce console log doit être supprimé juste d'avant de push, c'est certainement un oubli de ta part ;)

2023-07-10 20:58 UTC, xlincw0w commented on src/layouts/Clients/NewClient.js
> +    console.log("formData", formData);
Pareil ici :)

2023-07-10 21:44 UTC, HL-Abdallah commented
> Merci pour ton travail Abdallah tout est parfait j'ai juste une remarque en plus des console log si tu me le permet qui est de reset le formulaire après annulation, et aussi de créer les appels vers les endpoints avec les données même si elles ne sont pas prêt coté backend

Bien noté 👌 pour les logs, mais la PR est en mode Draft ( work in progress ), j'attends l'api pour la creation de la part de Dihia.
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/68193549/470dcc5a-f6da-4028-9b42-a2896e627f9a)

2023-07-13 18:37 UTC, xlincw0w commented on src/config/constants.js
> +export const API_URL = `${"http://localhost:8082"}/api/`;
Remettre `window.location.origin` pour que la requete sera intercepter et envoyer vers l'api

2023-07-15 12:23 UTC, xlincw0w requested changes
A part la requete de l'endpoint, tout est parfait et c'est meme fonctionnel

2023-07-15 12:23 UTC, xlincw0w commented on src/config/constants.js
> +export const API_URL = `${window.location.origin}/api/`;
Faut le remettre a /api/v1 et demander a dihia de corriger le endpoint de son API sinon ça risque de casser les call des autres developpeurs

2023-07-15 12:28 UTC, mchekini-check-consulting commented on src/config/constants.js
> +export const API_URL = `${window.location.origin}/api/`;
L'api client côté backend contient bien le : /api/v1

2023-07-15 13:05 UTC, merged