get and display all missions
mchekini-check-consulting/staff-manager-admin-ui pull request #6
Opened 2023-07-21 09:50 UTC by sidisaidkarim

created a folder public/api_mocks to mock api response as json files, when endpoint will be ready we juste change the url in the fetch function 
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/13240505/3af7cd64-0f6b-44fc-bfdb-4ec285458a9b)

used https://www.npmjs.com/package/react-toastify to display message when there is a server error ( the library was already installed by another dev)

screenshots from app
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/13240505/d443c645-1b79-4162-b493-5dd8d5c7421c)

![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/13240505/b85c2e4e-9817-4c45-91a7-5362f486ea79)

2023-07-21 13:49 UTC, MassiiNechiche reviewed
Remarque global : Utliser RTK query pour les api calls, un tag invalidation ce fera lors de la creation ou modification ce qui causera un auto refresh des données des missions sur l'UI.

2023-07-21 13:49 UTC, MassiiNechiche commented on src/layouts/missions/index.js
> +  useEffect(() => {
Hello Karim, Pour l'API call faudra utilisé RTK query qui est dèja en place à la place de fetch, tu peux créer un useQuery dans le fichier services/missions/missionSlice.js et l'exporter pour l'utiliser au lieu du useEffect.
Voici un exemple : 

<img width="619" alt="Screen Shot 2023-07-21 at 2 38 28 PM" src="https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/66673079/a64ca8ce-6cb2-458c-b2f9-c06a6a217ea8">

2023-07-21 13:49 UTC, MassiiNechiche commented on src/layouts/missions/index.js
> +        <ToastContainer />
Ici le toastContainer devrais se trouver au top level de l'application, sur App.js par exemple, pour en avoir qu'un seul au lieu de l'inclure dans tout les composant ou on utilise un toast.

2023-07-21 16:29 UTC, HL-Abdallah requested changes

2023-07-21 16:29 UTC, HL-Abdallah commented on src/layouts/missions/index.js
>      width: 150,
Merci pour ton travail Karim, j'ai 2 remarques

le seul problem avec `width` est que le colonnes ne s'afficherons pas bien dans les grand ecrans, exemple : 
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/68193549/490a5632-da52-4c25-942e-c27b75c7b058)

pour regler sa tu peut faire `flex` au lieu de `width`, et sa grandis avec la taille de l'écran : 
![image](https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/68193549/3cce92dc-31af-4edd-9486-5fc8d2c753ab)

j'ai mis un `flex : 1` sur touttes le colonnes, tu peut y aller sur un `flex : 2` pour la colonne email par exemple
y'a un exemple sur /clients

apart sa, utilise RTK Query comme on a fait pour la creation des missions, le `invalidateTags` est très très utile a mon avis, comme massi l'a mentionné.

2023-07-21 16:29 UTC, HL-Abdallah commented on src/layouts/missions/index.js
>      width: 150,
```suggestion
      {
    field: "startingDate",
    headerName: "Date de début ",
    // width: 150,
    flex: 1,
  },
  {
    field: "endingDate",
    headerName: "Date de fin ",
    // width: 150,
    flex: 1,
  },
```

2023-07-22 14:15 UTC, HL-Abdallah approved these changes

2023-07-22 15:41 UTC, MassiiNechiche approved these changes

2023-07-22 16:46 UTC, merged