search documents with mockData
mchekini-check-consulting/staff-manager-admin-ui pull request #7
Opened 2023-07-23 11:32 UTC by dihia-lyz

this pull request include:
 **a search bar with two filters(multi selects):**
  - collaborators names(using mocked data ).
  - documents types 
 **a table displaying filtered documents (using mocked data).**
 **a new service that calls the endpoint but is not yet used.**
  
<img width="716" alt="image" src="https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/77511394/d286d1c9-50fd-4da4-aa9e-afe519394738">

2023-07-23 19:25 UTC, Samlogy reviewed
Bonjour Dihia, 
Moi je valide ta PR, sauf que si tu pouvais par la suite remplacer le fetch avec RTK, avec le path mis à jour: /api/v1/justificatif/search

2023-07-23 19:32 UTC, MassiiNechiche requested changes
Tu peux pull la branch feat/SM-74 (API) et tu peux l'integrer et la tester en local. utilise RTK query pour appeler le endpoint "/justificatif/search".

2023-07-23 19:32 UTC, MassiiNechiche commented on public/mockedData/documentsList.json
> +    "documentType": "Piece d'identite",
Voici un exemple de réponse de l'api, essaie d'enlever document qui est répétitif ;)

<img width="291" alt="Screen Shot 2023-07-23 at 8 16 48 PM" src="https://github.com/mchekini-check-consulting/staff-manager-admin-ui/assets/66673079/ccbb7ab0-577e-486e-8a3f-2dbda0a7422a">

2023-07-23 19:32 UTC, MassiiNechiche commented on src/layouts/Justificatif/index.js
> +    fetch("./mockedData/documentsList.json")
Faudra utiliser RTK query au lieu de fetch pour les api calls.

2023-07-23 19:32 UTC, MassiiNechiche commented on src/services/justificatifs/justificatif.api.slice.js
> +export const documentApi = createApi({
ca serai mieux d'utiliser injectEndpoints au lieu de createApi (exemple dans missionSlice).

2023-07-23 19:35 UTC, xlincw0w requested changes

2023-07-23 19:35 UTC, xlincw0w commented on src/layouts/Justificatif/index.js
> +    fetch("./mockedData/collaboratorsList.json")
Pourquoi ne pas utiliser directement RTK query ? 
créer le hook useGetDocumentsQuery et y aller de la.

2023-07-23 19:35 UTC, xlincw0w commented on src/layouts/Justificatif/index.js
> +                  checked={selectedNames.some((selectedItem) => selectedItem.id === item.id)}
y a deux  **some** et une **map**, y a surement un meilleur moyen d'optimiser ça, 
au pire au moins pour le **some* tu peux faire ceci:
`let itemExist = selectedNames.some((selectedItem) => selectedItem.id === item.id)`

et utiliser le resultat.

2023-07-23 19:35 UTC, xlincw0w commented on src/layouts/Justificatif/index.js
> +              <MenuItem key={i} value={item}>
sur le key faut eviter les index de la boucle, vaut mieux utiliser item.id par exemple

2023-07-23 19:35 UTC, xlincw0w commented on src/layouts/Justificatif/index.js
> +                  checked={selectedTypes.some((selectedItem) => item.value === selectedItem.value)}
Pareil ici pour la méthode **some**.

2023-07-23 20:58 UTC, xlincw0w commented on src/layouts/Justificatif/index.js
> +                  checked={selectedTypes.some((selectedItem) => item.value === selectedItem.value)}
Les filtres ne fonctionnent pas aussi, je ne sais pas si c'est compris dans la user story

2023-07-23 20:58 UTC, xlincw0w commented
Les filtres ne fonctionnent pas aussi, je ne sais pas si c'est compris dans la user story

2023-07-24 19:51 UTC, dihia-lyz commented
La logique du filtre doit se faire côté back

Le dim. 23 juil. 2023 à 21:59, Khaled Khazem ***@***.***> a
écrit :

> Les filtres ne fonctionnent pas aussi, je ne sais pas si c'est compris
> dans la user story
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mchekini-check-consulting/staff-manager-admin-ui/pull/7#issuecomment-1646957880>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPLVYUHOSDAUNZFL4OJARTXRWGBHANCNFSM6AAAAAA2UORNLQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <mchekini-check-consulting/staff-manager-admin-ui/pull/7/c1646957880@
> github.com>
>

2023-07-25 19:46 UTC, closed without merging