Feat/sm 268
mchekini-check-consulting/staff-manager-admin-ui pull request #9
Opened 2023-07-23 20:59 UTC by MohamedAmine776

2023-07-23 21:39 UTC, mchekini-check-consulting approved these changes

2023-07-23 21:39 UTC, mchekini-check-consulting commented
@MohamedAmine776, faut rebase et traiter le conflit pour merger

2023-07-24 09:09 UTC, xlincw0w commented
@MohamedAmine776 Faut rebase y a un conflit

2023-07-24 10:09 UTC, HL-Abdallah requested changes

2023-07-24 10:09 UTC, HL-Abdallah commented on src/layouts/Clients/ClientList.js
> +            },
```
sorting: {
      sortModel: [{ field: 'id', sort: 'desc' }],
},
```

tu peut rajouter sa dans initial state ?

2023-07-24 10:09 UTC, HL-Abdallah commented on src/layouts/Clients/ClientList.js
> +import "react-toastify/dist/ReactToastify.css";
je pense que le conflict est la, dans les imports

2023-07-24 10:26 UTC, MohamedAmine776 commented on src/layouts/Clients/ClientList.js
> +            },
c'est fait

2023-07-24 10:26 UTC, MohamedAmine776 commented on src/layouts/Clients/ClientList.js
> +import "react-toastify/dist/ReactToastify.css";
conflit résolut

2023-07-24 11:20 UTC, merged